In [11]:
import numpy as np
np.arange(1,26).reshape(5,-1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
x = np.arange(1,26,dtype = 'float').reshape(5,-1)

In [72]:
np.max(x)
np.min(x)

1.0

In [67]:
def minfunc(y):
    y = float(np.min(y))
    print(y)
minfunc(x)

def maxfunc(y):
    print(float(np.max(y)))
maxfunc(x)

1.0
25.0


In [180]:
len(x)

2

In [74]:
(x - np.min(x)) / (np.max(x) - np.min(x))

array([[0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667],
       [0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ],
       [0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333],
       [0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667],
       [0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ]])

In [181]:
x = np.array([np.random.randint(0,100,4),np.random.randint(0,100,4)])
print(x)
def transpose(x):
    y = np.arange(0,len(x)*len(x[0])).reshape(len(x[0]) ,len(x) )
    print(y)
    for i in range(0,len(x)):
        for j in range(0, len(x[0])):
            y[j][i] = x[i][j]
    print(y)        
transpose(x)

[[21 43 49 45]
 [77 94 10 51]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[21 77]
 [43 94]
 [49 10]
 [45 51]]


In [131]:
m = [[1,2],[3,4],[5,6]] 
for row in m : 
    print(row) 
rez = [[m[j][i] for j in range(len(m))] for i in range(len(m[0]))] 
print("\n") 
print(rez)
for row in rez: 
    print(row) 

[1, 2]
[3, 4]
[5, 6]


[[1, 3, 5], [2, 4, 6]]
[1, 3, 5]
[2, 4, 6]



# Create a logistic regression model 


In [201]:
import pandas as pd
import numpy as np 

In [204]:
np.array([19,20,43,57,76,58,84,150,33,65])

array([ 19,  20,  43,  57,  76,  58,  84, 150,  33,  65])

In [210]:
df = pd.DataFrame(data = {'User ID':[15624510,15810944,15668575,15063246,15804002,15728773,15598044,15694829,15600575,15727311],
                          'Gender':['M','M','F','F','M','M','F','F','M','F'],  
                          'Age':[19,35,26,27,19,27,27,32,25,35],
                          'Salary':[19000,20000,43000,57000,76000,58000,84000,150000,33000,65000],
                          'Purchased':[0,0,0,0,0,0,0,1,0,0]})
                                             
                                             
                                             
                                             

In [212]:
df.head(2)

User ID Gender  Age  Salary  Purchased
0  15624510      M   19   19000          0
1  15810944      M   35   20000          0

In [215]:
x = df.iloc[:,[2,3]].values

In [219]:
y = df.iloc[:,[4]].values

In [221]:
import sklearn

In [227]:
print(x)
#print(y)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]]


In [225]:
from sklearn.model_selection import train_test_split

In [228]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

In [229]:
x_train

array([[    35,  65000],
       [    35,  20000],
       [    27,  84000],
       [    32, 150000],
       [    27,  57000],
       [    19,  19000],
       [    27,  58000]])

In [231]:
from sklearn.preprocessing import StandardScaler

In [232]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [234]:
x_test

array([[-0.54433105, -0.52799425],
       [-0.73484692, -0.7711495 ],
       [-1.87794214,  0.27441807]])

In [235]:
x_train

array([[ 1.17031177,  0.00694729],
       [ 1.17031177, -1.08725133],
       [-0.35381519,  0.46894227],
       [ 0.59876416,  2.07376691],
       [-0.35381519, -0.18757691],
       [-1.87794214, -1.11156685],
       [-0.35381519, -0.16326138]])

In [236]:
from sklearn.linear_model import LogisticRegression

In [238]:
classifier = LogisticRegression(random_state=0)

In [239]:
classifier.fit(x_train,y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [240]:
y_pred = classifier.predict(x_test)

In [241]:
from sklearn.metrics import accuracy_score

In [242]:
accuracy_score(y_test,y_pred)

1.0